# Generated by Django 5.1.14 on 2025-11-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Umum', max_length=100),
            preserve_default=False,
        ),
    ]
